<?php
 

 
function sab_resource_content_sync_install() {

    //Alters the page settings for the Main listings
    db_update('system')
    ->fields(array(
                    'schema_version' => 0,
      )
    )
    ->condition('name', 'sab_resource_content_sync')
    ->condition('type', 'module')
    ->execute();
    
}

 
///**
// * Implements hook_url_outbound_alter().
// */
//function sab_product_list_url_outbound_alter(&$path, &$options, $original_path) {

//    $fragmenets = explode('/', $path);

//    if(isset($fragmenets[0]) && $fragmenets[0] == 'product_list'){

//        $result = db_query('SELECT alias FROM {url_alias} WHERE source = :source', array($path))->fetchField();

//        if(!empty($result)){
            
//            $path = $result;
            
//        }
        
//    }

//}



///**
// * Implements hook_node_presave().
// */
//function sab_product_list_node_insert($node) {

//    try{

//        if($node->type == 'product_list'){

//            $url = drupal_get_query_parameters();

//            if(isset($url['plid'])){

//                $plid = $url['plid'];

//                $product_list = get_product_list_info_by_plid($plid);

//                if(isset($product_list->product_list)){

//                    db_update('eddy_product_list')->fields(array('has_node' => 1, 'nid' => $node->nid))->condition('plid', $plid)->execute();

//                }

//            }

//        }

//    }
//    catch(Exception $e){
        
//        if(module_exists('devel')){
//            dpm($e);
//        }
        
//    }

//}



function sab_resource_node_basic_properties(){

    $node = new stdclass;
    $node->type = "article_page";
    node_object_prepare($node);
    $node->language = LANGUAGE_NONE;
    $node->uid = 1;
    $node->promote = 0;
    $node->comment = 0;
    $node->status = 1;
    $node->body[$node->language][0]['format'] = 'full_html';
    return $node;
	
}


function sab_productlist_node_basic_properties(){

    $node = new stdclass;
    $node->type = "product_list";
    node_object_prepare($node);
    $node->language = LANGUAGE_NONE;
    $node->uid = 1;
    $node->promote = 0;
    $node->comment = 0;
    $node->status = 1;
    $node->body[$node->language][0]['format'] = 'full_html';
    return $node;
	
}


 



function sab_resource_content_sync_update_content_url_path($content)
{
    $modified_content = null;
	try
	{
        
        $modified_content= str_replace('src="/resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-02-84-59-Attached+Files/', 'width="250" src="/sites/default/files/images/', $content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-00-55-22-Attached+Files/', 'width="250" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-02-55-24-Attached+Files/', 'width="250" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-00-56-21-Attached+Files/', 'width="250" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-02-55-06-Attached+Files/', 'width="250" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/250x188/__key/CommunityServer.Components.UserFiles/00.00.00.55.22.Attached+Files/', 'width="250" height="188" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-00-55-24-Attached+Files/', 'width="250" height="188" src="/sites/default/files/images/', $modified_content) ;

        $modified_content=str_replace('src="/resized-image.ashx/__size/100x0/__key/communityserver-components-userfiles/00-00-00-55-22-Attached+Files/', 'width="100" src="/sites/default/files/images/', $modified_content) ;

        $modified_content=str_replace('src="/resized-image.ashx/__size/200x0/__key/communityserver-components-userfiles/00-00-00-55-22-Attached+Files/', 'width="200" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/200x0/__key/communityserver-components-userfiles/00-00-02-84-59-Attached+Files/', 'width="200" src="/sites/default/files/images/', $modified_content) ;

        $modified_content=str_replace('src="/resized-image.ashx/__size/255x0/__key/communityserver-components-userfiles/00-00-02-46-39-Attached+Files/', 'width="255" src="/sites/default/files/images/', $modified_content) ;


        $modified_content=str_replace('src="/resized-image.ashx/__size/300x0/__key/communityserver-components-userfiles/00-00-02-84-59-Attached+Files/', 'width="300" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/300x0/__key/communityserver-components-userfiles/00-00-02-46-39-Attached+Files/', 'width="300" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/350x0/__key/communityserver-components-userfiles/00-00-02-84-59-Attached+Files/', 'width="350" src="/sites/default/files/images/', $modified_content) ;

        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/CommunityServer.Components.UserFiles/00.00.00.56.56.Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/communityserver-components-userfiles/00-00-02-46-39-Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/communityserver-components-userfiles/00-00-02-84-59-Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/communityserver-components-userfiles/00-00-00-55-22-Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/CommunityServer.Components.UserFiles/00.00.00.21.00.Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/communityserver-components-userfiles/00-00-06-12-91-Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/550x0/__key/communityserver-components-userfiles/00-00-02-40-71-Attached+Files/', 'width="550" src="/sites/default/files/images/', $modified_content) ;

        $modified_content=str_replace('src="/resized-image.ashx/__size/560x400/__key/communityserver-components-postattachments/00-00-03-14-02-Attached+Files/', 'width="560" height="400" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/560x400/__key/communityserver-components-postattachments/00-00-03-14-03-Attached+Files/', 'width="560" height="400" src="/sites/default/files/images/', $modified_content) ;

        $modified_content=str_replace('src="/resized-image.ashx/__size/206x0/__key/communityserver-components-userfiles/00-00-02-84-59-Attached+Files/', 'width="206" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/resized-image.ashx/__size/600x0/__key/communityserver-components-userfiles/00-00-00-55-22-Attached+Files/', 'width="600" src="/sites/default/files/images/', $modified_content) ;
        $modified_content=str_replace('src="/cfs-file.ashx/__key/communityserver-components-userfiles/00-00-00-56-56-Attached+Files/', 'width="200" src="/sites/default/files/images/', $modified_content) ;
        
        
        //resized-image.ashx/__size/250x0/__key/communityserver-components-userfiles/00-00-00-55-24-Attached+Files/8182.italyrome.jpg
        $modified_content=str_replace('_2D00_', '-',$modified_content);



    }
	catch(Exception $e)
	{
		watchdog_exception('sab_resource_content_sync', $e);
	}

	return $modified_content;
}