<?php
/**
 * @file
 * Primary hook implementations for Metatag:Facebook.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function eddy_metatag_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements node_view().
 * Had to put this in a node view because the meta tags theme function was stripping HTML Tags.
 */
function eddy_metatag_node_view($node, $view){

    if(node_is_page($node) && isset($node->metatags[LANGUAGE_NONE]['open_field:field']['value'])){
        
        $markup = array(
            '#type' => 'markup',
            '#markup' => token_replace($node->metatags[LANGUAGE_NONE]['open_field:field']['value'], array('node' => $node)) . "\n",
        );
        drupal_add_html_head($markup, 'open_field');
        
    }

}

/**
 * Implements page_alter().
 * Only way to get the free field to show up on a Taxonomy Term page.
 */
function eddy_metatag_page_alter($page){

    if(arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2)) && arg(3) == NULL){
    
        $term = taxonomy_term_load(arg(2));
        
        if(!empty($term->metatags[LANGUAGE_NONE]['open_field:field']['value'])){
            $markup = array(
                '#type' => 'markup',
                '#markup' => token_replace($term->metatags[LANGUAGE_NONE]['open_field:field']['value'], array('taxonomy_term' => $term)) . "\n",
            );
            drupal_add_html_head($markup, 'open_field');
        }
        
    }

}