<?php

/**
 * Implements template_preprocess_html().
 */
function eddy_forms_engine_tag_preprocess_html(&$vars) {
    
    //Adds the responsive Body Class for the Program Template and the Wizard Drip Responsive.
    $vars['classes_array'][] = 'responsive';
    
}

/**
 * Implements hook_page_alter().
 */
function eddy_forms_engine_tag_page_alter($page) {
    
    if (!path_is_admin(current_path())) {

        drupal_add_js(drupal_get_path('module', 'eddy_forms_engine_tag') . "/js/script.js");
        drupal_add_js(array('application_id' => variable_get('eddy_core_application_id')), 'setting');
        drupal_add_js(array('application_name' => variable_get('eddy_core_application_name')), 'setting');

        //Includes the other Scripts needed for the form.
        if(module_exists('eddy_forms_engine')){ //For All SEO sites
            
            drupal_add_js(drupal_get_path('module', 'eddy_forms_engine') . "/js/cookie.js");
            drupal_add_js(drupal_get_path('module', 'eddy_forms_engine') . "/js/jquery.validate.js");
            drupal_add_js(drupal_get_path('module', 'eddy_forms_engine') . "/js/jquery.watermark.min.js");
            drupal_add_js(array('form_engine_url' => variable_get('eddy_forms_engine_service_domain')), 'setting');
            
        }else if(module_exists('form_wizard')){ //For Landingpages
            
            drupal_add_js(drupal_get_path('module', 'form_wizard') . "/js/cookie.js");
            drupal_add_js(drupal_get_path('module', 'form_wizard') . "/js/jquery.validate1.11.1.min.js");
            drupal_add_js(drupal_get_path('module', 'form_wizard') . "/js/jquery.watermark.min.js");
            drupal_add_js(array('form_engine_url' => variable_get("wizard_form_url")), 'setting');
            
        }else{
        
            dpm("Either the \"eddy_forms_engine\" or \"form_wizard module\" needs to be enabled for this module to work properly.");
        
        }
        

    }
    
}


/**
 * Implements hook_help().
 */
function eddy_forms_engine_tag_help($path, $arg) {
    
    switch ($path) {
        case 'admin/help#eddy_forms_engine_tag':
            
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This module allows you to place one Forms Engine Tag on a page. Below are the current placements and Properties.') . '</p>';
            $output .= '<h3>' . t('Program Form:') . '</h3>';
            $output .= '<p>' . t('If an Institution Id is present with no Template Id then we assume you would like to use a Program Template.') . '</p>';
            $output .= '<pre>';
            $output .= htmlentities("
            <!--Rendering Div-->
            <div class=\"stand-alone-form\" id=\"eddy-form-container\">&nbsp;</div>
            <!--/Rendering Div-->
            <!--FE Script Tag-->
            <script type=\"text/javascript\">
	            var FormsEngine = FormsEngine || {};
	            FormsEngine.InstitutionId = 14;
	            FormsEngine.InstitutionName = 'Abilene Christian University';
	            //FormsEngine.ProgramId = 4871; //(Optional)
            </script>
            <!--/FE Script Tag-->
            ");
            
            $output .= '</pre>';
            $output .= '<h3>' . t('Wizard Form:') . '</h3>';
            $output .= '<p>' . t('If a Template Id is present with no Institution Id then we assume you would like to use a Wizard.') . '</p>';
            $output .= '<pre>';
            $output .= htmlentities("
            <!--Rendering Div-->
            <div class=\"stand-alone-form\" id=\"eddy-form-container\">&nbsp;</div>
            <!--/Rendering Div-->
            <!--FE Script Tag-->
            <script type=\"text/javascript\">
	            var FormsEngine = FormsEngine || {};
	            FormsEngine.TemplateId = 91;
                    //FormsEngine.RenderingStrategy = 'WIZARDPROFESSIONALBOOTSTRAP'; //(Optional)
                    //FormsEngine.Theme = 'default'; //(Optional)
            </script>
            <!--/FE Script Tag-->
            ");
            $output .= '</pre>';
            
            $output .= '</pre>';
            $output .= '<h3>' . t('Program Wizard Form:') . '</h3>';
            $output .= '<p>' . t('If an Institution Id and Template Id are present then we assume you would like to use a Program Wizard.') . '</p>';
            $output .= '<pre>';
            $output .= htmlentities("
            <!--Rendering Div-->
            <div class=\"stand-alone-form\" id=\"eddy-form-container\">&nbsp;</div>
            <!--/Rendering Div-->
            <!--FE Script Tag-->
            <script type=\"text/javascript\">
	            var FormsEngine = FormsEngine || {};
	            FormsEngine.TemplateId = 277;
	            FormsEngine.InstitutionId = 14;
	            FormsEngine.InstitutionName = 'Abilene Christian University';
            </script>
            <!--/FE Script Tag-->
            ");
            $output .= '</pre>';

            return $output;
    }
    
}