<?php

/**
 * Implements hook_menu().
*/
function eddy_listings_ads_menu() {
	$items['admin/config/system/listing_ads'] = array(
		'title' => 'EDDY Listings Ads',
		'description' => 'Ads to be placed in the middle of listings (Degrees, Courses and Certificates',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('_eddy_listings_ads_get_form'),
		'access arguments' => array('administer_eddy_listings_ads'),
		'type' => MENU_NORMAL_ITEM,
	);
 
	return $items;
}

function eddy_listings_ads_permission() {
  return array(
    'administer_eddy_listings_ads' => array(
      'title' => 'Administer Listings Ads Settings'
    ),
  );
}

function _eddy_listings_ads_get_form($form, &$form_state) {
  
	$form['#submit'][] = '_eddy_listings_ads_save';

	$form['eddy_listings_ads_degrees_field'] = array(
		'#type' => 'textarea',
		'#title' => t('Degrees Listings Ads'),
		'#description' => t('Advertisment to be placed in the middle of the listings on Degrees Pages'),
		'#default_value' => variable_get('eddy_listings_ads_degrees'),
	);
	$form['eddy_listings_ads_courses_field'] = array(
		'#type' => 'textarea',
		'#title' => t('Courses Listings Ads'),
		'#description' => t('Advertisment to be placed in the middle of the listings on Courses Pages'),
		'#default_value' => variable_get('eddy_listings_ads_courses'),
	);
	$form['eddy_listings_ads_certificates_field'] = array(
		'#type' => 'textarea',
		'#title' => t('Certificates Listings Ads'),
		'#description' => t('Advertisment to be placed in the middle of the listings on Certificates Pages'),
		'#default_value' => variable_get('eddy_listings_ads_certificates'),
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save Listings Ads'),
	);

	return $form;
}

function _eddy_listings_ads_save($form, &$form_state){
	
	variable_set('eddy_listings_ads_degrees', $form_state['values']['eddy_listings_ads_degrees_field']);
    variable_set('eddy_listings_ads_courses', $form_state['values']['eddy_listings_ads_courses_field']);
	variable_set('eddy_listings_ads_certificates', $form_state['values']['eddy_listings_ads_certificates_field']);
    
	drupal_set_message(t('The EDDY Listings Ads have been saved.'));	
}


function eddy_listings_ads_preprocess_html(&$variables) {

	if(variable_get("eddy_listings_ads_degrees") != null) {
		$element = array(
			'#type' => 'markup',
			'#markup' => variable_get('eddy_listings_ads_degrees'),
			'#weight' => 10,
		);
					
	}
	
	if(variable_get("eddy_listings_ads_courses") != null) {
		$element = array(
			'#type' => 'markup',
			'#markup' => variable_get('eddy_listings_ads_courses'),
			'#weight' => 50,
		);
					
	}
	if(variable_get("eddy_listings_ads_certificates") != null) {
		$element = array(
			'#type' => 'markup',
			'#markup' => variable_get('eddy_listings_ads_certificates'),
			'#weight' => 99,
		);
					
	}

}

function eddy_listings_ads_enable() {


}