<?php

/**
 * Implements hook_page_alter().
 */
function sab_metatag_page_alter($page){

    $qs = array_change_key_case(drupal_get_query_parameters($_GET, array('q', 'page')), CASE_LOWER);

    $product_list = get_sab_product_list_current_product_list();

    if(isset($product_list->product_list) && (!$product_list->product_list->has_node || isset($qs["in"]))){

        sab_metatag_set_dynamic_meta_tags($product_list);

    }

}


/**
 * Implements hook_html_head_alter().
 */
function sab_metatag_html_head_alter(&$variables){

    if(isset($variables['program_details_canonical'])){
        $variables['program_details_canonical']['#access'] = TRUE;
    }

}


function sab_metatag_set_dynamic_meta_tags($product_list){

    if(isset($product_list->listing_options['type'][0])){

        $title = "";
        $description = "";
        $country = "Worldwide";
        $city = "";
        $level = "";
        $term = "";
        $specialty = "";
        $duration = "";
        $intensive_language = "";
        $work_type = "";
        $audience = "";


        $titles = $product_list->titles;

        if(isset($titles['country']) && $titles['country']){
            
            $country = $titles['country'];

        }else if(isset($titles['state']) && $titles['state']){
            
            $country = $titles['state'];
            
        }

        if(isset($titles['level'])){
            
            $level = $titles['level'];

        }

        if(isset($titles['specialty'])){
            
            $specialty = $titles['specialty'];

        }

        if(isset($titles['term'])){
            
            $term = $titles['term'];

        }

        if(isset($titles['type'])){
            
            $program_type = $titles['type'];

        }

        if(isset($titles['audience'])){
            
            $audience = $titles['audience'];

        }

        if(isset($titles['intensive_language'])){
            
            $intensive_language = $titles['intensive_language'];

        }

        foreach($product_list->relationships_terms as $k => $v){
            
            if($v->vocabulary_machine_name == 'cities'){
                $city = 'in ' . $v->name . ',';
            }

            if($v->vocabulary_machine_name == 'durations'){
                $duration = $v->name;
            }

            if($v->vocabulary_machine_name == 'work_types'){
                $work_type = $v->name;
            }

        }
        
        switch($product_list->listing_options['type'][0]){
            
            case 4: //Study Abroad

                if($titles['level'] != "Undergraduate"){
                    $titles['level'] = "";
                }

                if(empty($city) && $country != "Worldwide"){
                    $country = "in $country";
                }

                $title .= "$term $specialty $program_type $level Programs $city $country";
                $description .= "$specialty $level $program_type Programs $city $country. Search verified $specialty $duration $program_type $level programs with reviews and scholarship information.";

                break;

            case 1: //Full Degree

                if(empty($city) && $country != "Worldwide"){
                    $country = "in $country";
                }

                if(empty($specialty)){
                    
                    $specialty = "a Degree";

                }else{

                    if (in_array(substr($specialty, 0, 1), array('A', 'E', 'I', 'O', 'U'))){

                        $specialty = "an $specialty";

                    }else{

                        $specialty = "a $specialty";

                    }
                    
                }

                $title .= "Earn $specialty $level $city $country";

                if($specialty == "a Degree"){
                    
                    $specialty = "Degree";

                }

                $description .= "Review $specialty $level Programs $city $country. Search Study Abroad Degree programs $city $country through our verified listings.";

                break;

            case 5: //Volunteer Abroad

                $title .= "$program_type $city $country | $work_type $duration Programs, Reviews, Funding";

                if(!empty($duration)){
                    
                    $duration = "for a $duration";

                }

                $description .= "Volunteer $city $country $duration program. Make a difference volunteering in $city $country with one of our certified programs.";

                break;
            
            case 6: //Teach Abroad
                
                if(empty($city) && $country != "Worldwide"){
                    $country = "in $country";
                }

                if(!empty($audience)){
                    
                    $audience = "for $audience";

                }else{
                    
                    $audience = "Job Placements";
                    
                }

                if(!empty($duration)){
                    
                    $duration = "for $duration";

                }

                $title .= "Teach $city $country $audience $duration";

                $description .= "Teach abroad $city $country verified job placements $city $country. $audience $duration";

                break;
            
            case 7: //Intern Abroad

                if(empty($city) && $country != "Worldwide"){
                    $country = "in $country";
                }

                if(!empty($work_type)){
                    $work_type = "with a focus on $work_type";
                }
                
                $title .= "$program_type $city $country $work_type";

                $description .= "$program_type $city $country $work_type";
                
                break;

            case 8: //Intensive Language

                if(empty($city) && $country != "Worldwide"){
                    $country = "in $country";
                }

                $title .= "$duration $program_type $intensive_language $city $country";

                $description .= "$duration $program_type $intensive_language $city $country";

                break;
            
        }

        $title = trim(preg_replace("/[[:blank:]]+/"," ",$title));

        drupal_set_title($title);

        $element = array(
          '#tag' => 'meta', 
            '#attributes' => array(
                'name' => 'description',
                'content' => $title,
            ),
        );
        drupal_add_html_head($element, 'meta_description');

    }

}