<?php
     
function _sab_get_user_role_id_by_name($role_name){
    
    $output= 0; 
    if(!empty($role_name)) {
     
        $query = db_select('role', 'r'); 
        $query->fields('r', array('rid'))
              ->condition('r.name', $role_name); 
        
        $result = $query->execute()->fetchAll();   
       
        if(!empty($result)) {
            $output =  $result[0]->rid; 
        }
    
    }
   
    return $output; 
}
