<?php

/**
 * Implements hook_menu().
 */
function sab_institution_details_menu() {

    $items = array();

    $items["institutions/%"] = array(
          'page callback' => 'sab_institution_details_get_details',
          'access callback' => TRUE
    );

    return $items;

}

/**
 * Implements hook_permissions().
 */
function sab_institution_details_permission() {

    return array(
     'sab_institution_can_view_unpublished' => array(
       'title' => 'User can view unpublished Institutions'
     ),
   );

}

/**
 * Implements hook_theme().
 */
function sab_institution_details_theme() {

    return array(
      'sab_institution_details_block_page' => array(
        'variables' => array('details' => NULL),
        'template' => 'sab-institution-details-block',
      ),

      //'sab_institution_search_filter_block_page' => array(
      //  'variables' => array('details' => NULL),
      //  'template' => 'sab-institution-search-filter-block',
      //),

	);

}

/**
 * Implements hook_block_info().
// */
function sab_institution_details_block_info() {
    $blocks = array();

    $blocks['sab_institution_details_logo'] = array(
        'info' => t('SAB: Institution Details Page logo'),
        'title' => 'SAB: Institution Details Page logo',
        'cache' => DRUPAL_CACHE_PER_PAGE,
    );
    $blocks['sab_institution_details_title'] = array(
        'info' => t('SAB: Institution Details Page Title'),
        'title' => 'SAB: Institution Details Page Title',
        'cache' => DRUPAL_CACHE_PER_PAGE,
    );
    $blocks['sab_institution_details'] = array(
       'info' => t('SAB: Institution Details'),
       'title' => 'SAB: Institution Details',
       'cache' => DRUPAL_CACHE_PER_PAGE,
   );

    return $blocks;

}

/**
 * Implements hook_block_view().
 */
function sab_institution_details_block_view($delta = '') {

    $block = array();

	switch ($delta) {

        case 'sab_institution_details_logo':
            $block['content'] = _sab_institution_details_block_logo();
			break;
        case 'sab_institution_details_title':
            $block['content'] = _sab_institution_details_block_title();
			break;
        case 'sab_institution_details':
            $block['content'] = _sab_institution_details_block_contents();
			break;

	}

	return $block;

}

/**
 * Implements hook_flush_caches().
 */
function sab_institution_details_flush_caches() {
    cache_clear_all('institution_', 'cache_sab_institution_details', TRUE);
}

/**
 * Get Instution Details for Block
 */
function _sab_institution_details_block_contents() {

    try{
        $details = sab_institution_details_get_details();

        $markup = '';

        if (!empty($details) && isset($details->schoolDetails->InstitutionId)){

            $markup .= '<div class="sab-school-details">';
            $markup .= '<div class="sab-school-detail-description">';

            $desc = (!empty($details->schoolDetails->InstitutionDescriptionInternational)) ? $details->schoolDetails->InstitutionDescriptionInternational : $details->schoolDetails->InstitutionDescription;

            $markup .= $desc .'</div></div>';

        }
    }
    catch(Exception $e){

        dpm($e);

    }

    return $markup;

}

/**
 * Gets Institution Details Logo .
 */
function _sab_institution_details_block_logo() {

    $markup = '';
    try{
        $details = sab_institution_details_get_details();

        if (!empty($details) && isset($details->schoolDetails->InstitutionId)){
           
            $logo_markup = eddy_build_institution_logo($details->schoolDetails, '120', array('link' => null, 'linkTitle' => 'Learn more about ' . $details->schoolDetails->InstitutionName, 'attributes' => array('itemprop' => 'logo')));
            $markup .='<div class="logo-holder-details">'.$logo_markup.'</div>';

        }
    }
    catch(Exception $e){

        dpm($e);

    }

    return $markup;
}

/**
 * Gets Institution Details Title  .
 */
function _sab_institution_details_block_title() {

    $markup = '';
    try{
        $details = sab_institution_details_get_details();

        if (!empty($details) && isset($details->schoolDetails->InstitutionId)){

            $markup .= '<div class="institutiondetail-header" itemscope itemtype="http://schema.org/EducationalOrganization">';
            $markup .= '<div class="col-xs-12 name-section">';
            $markup .= '<h2 class="provider-name"><span itemprop="name">'.$details->schoolDetails->InstitutionName.'</span></h2>';
            $markup .= '</div>';
            $markup .= '</div>';
            $markup .='';

        }
    }
    catch(Exception $e){

        dpm($e);

    }

    return $markup;

}
/**
 * Get School Details.
 */
function sab_institution_details_get_details(){

    $output = new stdclass;

	if(arg(0) == 'node' && is_numeric(arg(1))) {

		$nid = arg(1);
		$node = node_load($nid);

        if($node->type == 'institution' && isset($node->field_external_id[LANGUAGE_NONE][0]['value'])){

			$schoolid = $node->field_external_id[LANGUAGE_NONE][0]['value'];

			$schoolDetails = sab_institution_details_get_school_details($schoolid);

			if (!empty($schoolDetails)){

                if(isset($node->field_school_desc_other[LANGUAGE_NONE][0]['value'])){
                    $schoolDetails->description = $node->field_school_desc_other[LANGUAGE_NONE][0]['value'];
                }

                $schoolDetails->entity_id = $node->nid;
				$schoolDetails->node = $node;

                $output->schoolDetails = $schoolDetails;

                //$programDetails = sab_institution_details_get_programs($schoolid);

                //if(!empty($programDetails)) {

                //    $output->programDetails =  $programDetails;
                //}


			}
			else{

                if(!user_access('sab_institution_can_view_unpublished')){

                    drupal_goto('<front>');


				}

			}

        }

	}

    return $output;

}

/**
 * Return school details from the Matching Engine Service.
 */
function sab_institution_details_get_school_details($institutionid) {

	$schoolDetails = new stdclass;

    $cid = 'institution_' . $institutionid;

    $cacheOptions = array(
        'cid' => $cid,
        'table' => 'cache_sab_institution_details',
        'duration' => time() + 300,
        'enabled' => TRUE, //Disabled for Testing
    );

    if ($cacheOptions['cid'] != '' && variable_get('eddy_services_cache_is_enabled') && $cache = cache_get($cid, $cacheOptions['table'])){

        if ($cache->expire > REQUEST_TIME && get_current_state() != 'beta_'){
            $results = $cache->data;
        }
        else
            $results = eddy_services_get_institution_details($institutionid, "", $cacheOptions);
    }
    else{
        $results = eddy_services_get_institution_details($institutionid, "", $cacheOptions);
    }


    if(!empty($results->GetInstitutionDetailsResult->InstitutionDetails)){
        $schoolDetails = $results->GetInstitutionDetailsResult->InstitutionDetails;
    }

    return $schoolDetails;

}


/**
 * Return program details from the Matching Engine Service.
 */
//function sab_institution_details_get_programs($institutionid) {

//    $programDetails = new stdclass;

//    $cacheOptions = array();
//    $results = eddy_services_get_listings(array('institution' => array($institutionid)), 'GetPrograms', $cacheOptions);

//    if(!empty($results->GetProgramsResult->ProgramList)){
//        $programDetails = $results->GetProgramsResult->ProgramList;
//    }

//    return $programDetails;

//}