<?php

function eddy_restore_install() {
    
	if(module_exists('cdn')){
		module_disable(array('cdn'));
	}
	
	if(module_exists('memcache')){
		module_disable(array('memcache'));
	}
	
	if(module_exists('memcache_admin')){
		module_disable(array('memcache_admin'));
	}
	
	if(module_exists('elearners_pixels')){
		module_disable(array('elearners_pixels'));
	}
	
	//Reset Admin Password to "a"
	$AdminUser = user_load('1');
	$AdminUser->pass = 'a';
	user_save((object)array('uid' => $AdminUser->uid), (array)$AdminUser);
	
	drupal_set_message('CDN and Memcache modules have been disabled. The Admin Password has been set to "a"');
	
}