<?php

/**
 * Implements hook_menu().
 */
function sab_popular_city_country_menu() {
    
    $items['admin/structure/popular_city_country'] = array(
        'title' => 'Manage Popular Countries & Cities',
        'description' => 'Allows to manage popular countries and cities.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sab_popular_country_list_form'),
        'access arguments' => array('administer popular cities and countries'),
        'file' => 'sab_popular_city_country.admin.inc',
    );
 
    $items['admin/structure/popular_city_country/manage/country'] = array(
       'title' => 'Popular Countries',
       'description' => 'Allows to manage popular Countries.',
       'type' => MENU_DEFAULT_LOCAL_TASK,
       'weight' => 10,
     );
  
    $items['admin/structure/popular_city_country/manage/city'] = array(
      'title' => 'Popular cities',
      'description' => 'Allows to manage popular cities.',
      'page callback' => 'sab_popular_cities_page',
      'access arguments' => array('administer popular cities and countries'),
      'file' => 'sab_popular_city_country.admin.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 20,
    );

	return $items;

}

function sab_popular_cities_page() {
    $output = array();
    
    $output['filter'] = drupal_get_form('sab_popular_city_filter_form');
    $output['list'] = drupal_get_form('sab_popular_city_list_form');
 
    return $output;
}

/**
 * Implements hook_permission().
 */
function sab_popular_city_country_permission() {
	return array(
		'administer popular cities and countries' => array(
		  'title' => 'Administer popular cities and countries settings.'
		),
	);
}


function sab_popular_city_update($tids, $unset_tids) {

    $transaction = db_transaction();
    try {
        
        if (!empty($tids)) {
            $cities = sab_popular_city_country_load_multiple($tids);

               foreach ($cities as $city) {
               
                    if($city != FALSE)
                    {
                        $city->field_is_popular[LANGUAGE_NONE][0]['value'] = 1;
                        taxonomy_term_save($city);
                    }

                }
       
        }
        if (!empty($unset_tids)) { 
        
            $unset_countries = sab_popular_city_country_load_multiple($unset_tids);
        
            foreach ($unset_countries as $country) {
            
                if($country != FALSE)
                {
                    $country->field_is_popular[LANGUAGE_NONE][0]['value'] = 0;
                    taxonomy_term_save($country);
                }

            }
        
        }      
    }
    catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('sab_popular_city', $e);
        throw $e;
    }
}
    
function sab_popular_country_update($tids, $unset_tids) {
    
    $transaction = db_transaction();
    try { 
     
        if (!empty($tids)) {

            $countries = sab_popular_city_country_load_multiple($tids);

            foreach ($countries as $country) {
               
                if($country != FALSE)
                {
                    $country->field_is_popular[LANGUAGE_NONE][0]['value'] = 1;
                    taxonomy_term_save($country);
                }

            }
             
        }


        if (!empty($unset_tids)) { 
            
            $unset_countries = sab_popular_city_country_load_multiple($unset_tids);
         
            foreach ($unset_countries as $country) {
                
                if($country != FALSE)
                {
                    $country->field_is_popular[LANGUAGE_NONE][0]['value'] = 0;
                    taxonomy_term_save($country);
                }

            }
            
        }
    }
    catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('sab_popular_country', $e);
        throw $e;
    }
} 