<?php
 

 
/**
 * Implements hook_cron().
 */
function sab_blog_sync_install() {

     
    db_update('system')
    ->fields(array(
        'schema_version' => 0,
      )
    )
    ->condition('name', 'sab_blog_sync')
    ->condition('type', 'module')
    ->execute();
    
}


 

  


//function sab_blog_comments($threadid)
//{
 
//    try
//    {
        
//        db_set_active('sab_new');
        
//        $results = db_select('vw_sab_blogcomments', 'c')
//        ->fields('c')
//        ->condition('ThreadID', $threadid)
//        ->execute()
//        ->fetchAll();
        
//        return $results;
        
 
//    }
//    catch(Exception $e)
//    {
//        watchdog_exception('sab_resource_content_sync', $e);
//    }

//    return null;
//}

function sab_blog_clean_url_segment($url){
	$url = preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', $url);
	$url = strtolower(trim($url, '-'));
	$url = preg_replace("/[\/_|+ -]+/", '-', $url);
	return $url;
}
